# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
data:
  auth_method: offline-token
  ocmAPIToken: ENCRYPTED_TOKEN
kind: Secret
metadata:
  labels:
    cluster.open-cluster-management.io/cloudconnection: ""
    cluster.open-cluster-management.io/provider: crh
  name: ocm-api-token
  namespace: NAMESPACE
type: Opaque
